### ISSUE TITLE
Belkide node-minecraft protocol kullanabilirsin :)

### ISSUE THREAD

**Issue by KaffinPX** [uAliFurkanY/minecraft-discord-bridge#1]
Selam ben PrismarineJS in tek Türk contributoruyum güzel botmuş kolay gelsin.
Node-minecraft-protocol ile çok fazla sayıda aynı anda botu kullanabilirsin.

**Comment by slonkazoid** [comment]
Belki sonra kullanırım. Ama şu an sadece v2'yi çalıştırmaya uğraşıyorum.

**Comment by KaffinPX** [comment]
Kolay gelsin yardım istersen discord: KaffinPX#1744
